# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:24:30+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class CountryRead(BaseModel):
    confirmed: Optional[int] = None
    critical: Optional[int] = None
    deaths: Optional[int] = None
    lastChange: Optional[datetime] = None
    lastUpdate: Optional[datetime] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    name: Optional[str] = None
    recovered: Optional[int] = None


class DailyReportRead(BaseModel):
    pass


class Format(Enum):
    json = 'json'
    xml = 'xml'


class CountryGetResponseItem(BaseModel):
    confirmed: Optional[int] = None
    country: Optional[str] = None
    critical: Optional[int] = None
    deaths: Optional[int] = None
    lastChange: Optional[datetime] = None
    lastUpdate: Optional[datetime] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    recovered: Optional[int] = None


class CountryGetResponse(RootModel[List[CountryGetResponseItem]]):
    root: List[CountryGetResponseItem]


class CountryGetResponse1(RootModel[List[CountryGetResponseItem]]):
    root: List[CountryGetResponseItem]


class CountryAllGetResponseItem(BaseModel):
    confirmed: Optional[int] = None
    country: Optional[str] = None
    critical: Optional[int] = None
    deaths: Optional[int] = None
    lastChange: Optional[datetime] = None
    lastUpdate: Optional[datetime] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    recovered: Optional[int] = None


class CountryAllGetResponse(RootModel[List[CountryAllGetResponseItem]]):
    root: List[CountryAllGetResponseItem]


class CountryAllGetResponse1(RootModel[List[CountryAllGetResponseItem]]):
    root: List[CountryAllGetResponseItem]


class CountryCodeGetResponseItem(BaseModel):
    confirmed: Optional[int] = None
    country: Optional[str] = None
    critical: Optional[int] = None
    deaths: Optional[int] = None
    lastChange: Optional[datetime] = None
    lastUpdate: Optional[datetime] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    recovered: Optional[int] = None


class CountryCodeGetResponse(RootModel[List[CountryCodeGetResponseItem]]):
    root: List[CountryCodeGetResponseItem]


class CountryCodeGetResponse1(RootModel[List[CountryCodeGetResponseItem]]):
    root: List[CountryCodeGetResponseItem]


class HelpCountriesGetResponseItem(BaseModel):
    alpha_2_code: Optional[str] = Field(None, alias='alpha-2-code')
    alpha_3_code: Optional[str] = Field(None, alias='alpha-3-code')
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    name: Optional[str] = None


class HelpCountriesGetResponse(RootModel[List[HelpCountriesGetResponseItem]]):
    root: List[HelpCountriesGetResponseItem]


class HelpCountriesGetResponse1(RootModel[List[HelpCountriesGetResponseItem]]):
    root: List[HelpCountriesGetResponseItem]


class DateFormat(Enum):
    YYYY_MM_DD = 'YYYY-MM-DD'
    YYYY_DD_MM = 'YYYY-DD-MM'
    DD_MM_YYYY = 'DD-MM-YYYY'
    MM_DD_YYYY = 'MM-DD-YYYY'


class ProvinceItem(BaseModel):
    active: Optional[int] = None
    confirmed: Optional[int] = None
    deaths: Optional[int] = None
    recovered: Optional[int] = None


class ReportCountryAllGetResponseItem(BaseModel):
    country: Optional[str] = None
    date: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    province: Optional[List[ProvinceItem]] = None


class ReportCountryAllGetResponse(RootModel[List[ReportCountryAllGetResponseItem]]):
    root: List[ReportCountryAllGetResponseItem]


class ReportCountryAllGetResponseItem1(BaseModel):
    country: Optional[str] = None
    date: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    province: Optional[List[ProvinceItem]] = None


class ReportCountryAllGetResponse1(RootModel[List[ReportCountryAllGetResponseItem1]]):
    root: List[ReportCountryAllGetResponseItem1]


class ReportCountryCodeGetResponseItem(BaseModel):
    country: Optional[str] = None
    date: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    province: Optional[List[ProvinceItem]] = None


class ReportCountryCodeGetResponse(RootModel[List[ReportCountryCodeGetResponseItem]]):
    root: List[ReportCountryCodeGetResponseItem]


class ReportCountryCodeGetResponseItem1(BaseModel):
    country: Optional[str] = None
    date: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    province: Optional[List[ProvinceItem]] = None


class ReportCountryCodeGetResponse1(RootModel[List[ReportCountryCodeGetResponseItem1]]):
    root: List[ReportCountryCodeGetResponseItem1]


class ReportCountryNameGetResponseItem(BaseModel):
    country: Optional[str] = None
    date: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    province: Optional[List[ProvinceItem]] = None


class ReportCountryNameGetResponse(RootModel[List[ReportCountryNameGetResponseItem]]):
    root: List[ReportCountryNameGetResponseItem]


class ReportCountryNameGetResponseItem1(BaseModel):
    country: Optional[str] = None
    date: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    province: Optional[List[ProvinceItem]] = None


class ReportCountryNameGetResponse1(RootModel[List[ReportCountryNameGetResponseItem1]]):
    root: List[ReportCountryNameGetResponseItem1]


class ReportTotalsGetResponseItem(BaseModel):
    active: Optional[int] = None
    confirmed: Optional[int] = None
    critical: Optional[int] = None
    date: Optional[str] = None
    deaths: Optional[int] = None
    recovered: Optional[int] = None


class ReportTotalsGetResponse(RootModel[List[ReportTotalsGetResponseItem]]):
    root: List[ReportTotalsGetResponseItem]


class ReportTotalsGetResponse1(RootModel[List[ReportTotalsGetResponseItem]]):
    root: List[ReportTotalsGetResponseItem]


class TotalsGetResponseItem(BaseModel):
    confirmed: Optional[int] = None
    critical: Optional[int] = None
    deaths: Optional[int] = None
    lastChange: Optional[datetime] = None
    lastUpdate: Optional[datetime] = None
    recovered: Optional[int] = None


class TotalsGetResponse(RootModel[List[TotalsGetResponseItem]]):
    root: List[TotalsGetResponseItem]


class TotalsGetResponse1(RootModel[List[TotalsGetResponseItem]]):
    root: List[TotalsGetResponseItem]
